#!/bin/bash

if [ -L ${BASH_SOURCE[0]} ]
then
        LINKED=$( readlink "${BASH_SOURCE[0]}" )
        DIR="$( cd "$( dirname "${LINKED}" )" && pwd )"
else
        DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

java -jar $DIR/target/gallery-*-standalone.jar $@
